### ISSUE TITLE
Use the discriminator field only in the Codecs

### ISSUE THREAD

**Issue by jochumb** [ghostbuster91/sttp-openapi-generator#185]
In the environment where we use this plugin, our Open API spec contains a schema with a discriminator to differentiate between the different types a request can be. The code generated by the plugin uses this discriminator in the Codecs and on the model itself. Precisely like the example from the [readme](https://github.com/ghostbuster91/sttp-openapi-generator#discriminators). In the example, the `name` field is a discriminator in de Codecs and a field on the case classes.

We would like to have the option (configurable?) to have the discriminator only be part of the Codecs and not be a field on the model.

This is because the discriminator is purely technical in our domain and doesn't offer any value outside of decoding JSON to our model. In any instance of a case class, the discriminator field also can only be one value to be a valid instance that can be encoded and decoded. By having the field settable by the creator of the instance, while it should always be the same value, we make usage of this model more error-prone.

**Comment by ghostbuster91** [comment]
I see your point. You are right. I think that it should've been done like that in the first place. I wonder what are the cases when you would like to still use the old behavior. Since old behavior is already implemented we can leave it behind some configuration flag and make the new behavior the default one.

I think that it shouldn't not be hard to do, but I can't say for sure since my memory about that codebase almost evaporated. I can take a look it during the weekend.

**Comment by jochumb** [comment]
I’ll gladly give it a go when I’m back from holiday, if you like.

I haven’t been able to think of a use case where I would like to have the discriminator property and its value on a model instance yet. So maybe it’s worth considering avoiding the additional complexity of making it configurable, and introduce a new mayor version that is not backwards compatible in this regard.

**Comment by ghostbuster91** [comment]
I am not going to turn down such a generous offer, make yourself as at home :)

**Comment by jochumb** [comment]
Opened a PR here: https://github.com/ghostbuster91/sttp-openapi-generator/pull/200

**Comment by jochumb** [comment]
Something to consider for a future release; 
I think currently this generator does not support the use of a discriminator in an `allOf` construction, see the example at the end of the `Discriminator Object` section of the spec: https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#discriminator-object . We haven't taken into account this part of the spec when preparing a PR for this issue. 
If you see possibilities of refactoring this change in a way that would make it more compatible with a way to support this part of the spec, we're open to suggestions.

**Comment by ghostbuster91** [comment]
I made a commit to your PR. After some small adjustments it seems that this case is also covered :) Unless, I misunderstood you.

**Comment by jochumb** [comment]
I noticed there isn't a release yet containing this change. Anything I can do to lighten the workload? Maybe make a suggestion for readme changes?
Thanks!

**Comment by ghostbuster91** [comment]
Sorry for this delay, I was preoccupied with other matters. I've just pushed a new tag (hopefully that's all it takes to make a new release :sweat_smile: )
